version: '2.4'
services:
  dev:
    image: gfw/api-gtiles
    build:
      context: .
      target: development
    env_file: ./dev/env
    command: npm start
    volumes:
      - "./src:/opt/project/src"
      - "./spec:/opt/project/spec"
      - "./package.json:/opt/project/package.json"
      - "./.eslintrc.js:/opt/project/.eslintrc.js"
      - "./dev:/opt/project/dev"
    ports:
      - "8080:8080"
      - "9229:9229"
    environment:
      - NODE_ENV=development

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "3000:8080"
    environment:
      - URL=http://localhost:8080/api
